### PR TITLE
Teammate detection

### LINKED ISSUE #48: Read teammates and use this knowledge to make better decisions
Reading teammates could be helpful for:
- Making better decisions on moves, particularly those such as Wide Guard that rely on your teammates contributing damage,
- Choosing a path that the team is good against and is also good against the final boss, and
- Choosing whether to take a new rental Pokemon or allow a teammate the opportunity to replace their Pokemon.
Note that the team would ideally be read in the den so it is always up-to-date.

### LINKED ISSUE #51: Read health of your current pokemon / teammates / boss
That would allow to better pick the moves, know when to swap for an other pokemon, etc

### PR DESCRIPTION
**Pull request by ercdndrs**
- Add ability to detect teammates from their sprites that are shown while navigating the den.
- Add detection of team HP.

### CODE REVIEW

**Comment by pifopi** [comment]
You should be able to remove the check for your own pokemon in battle function, line 220 of auto_max_lair.py (I'm on phone right now and I can't comment there :( )

**Comment by ercdndrs** [comment]
> You should be able to remove the check for your own pokemon in battle function, line 220 of auto_max_lair.py (I'm on phone right now and I can't comment there :( )

Good catch. I'm not super confident about the sprite matching compared to the method we had before. I may leave that code in until we see that the detection after the scientist is robust.

**Comment by pifopi** [comment]
> 
> 
> > You should be able to remove the check for your own pokemon in battle function, line 220 of auto_max_lair.py (I'm on phone right now and I can't comment there :( )
> 
> Good catch. I'm not super confident about the sprite matching compared to the method we had before. I may leave that code in until we see that the detection after the scientist is robust.

Hmm but that will be dead code because Pokemon will no longer be None :
run.pokemon = run.team_pokemon[0]

I'm willing to try the new code ^^ also swap for scientist doesn't happen that often so i guess it's not a huge deal ?

**Review by pifopi — APPROVED** [review]

**Comment by ercdndrs** [comment]
> > > You should be able to remove the check for your own pokemon in battle function, line 220 of auto_max_lair.py (I'm on phone right now and I can't comment there :( )
> > 
> > 
> > Good catch. I'm not super confident about the sprite matching compared to the method we had before. I may leave that code in until we see that the detection after the scientist is robust.
> 
> Hmm but that will be dead code because Pokemon will no longer be None :
> run.pokemon = run.team_pokemon[0]
> 
> I'm willing to try the new code ^^ also swap for scientist doesn't happen that often so i guess it's not a huge deal ?

That's fair. When I last tested it the timing was off for the scientist and I think it would often read too late. In that case all the Pokemon were thought to be Abomasnow which is clearly wrong. I think I fixed the timings but I haven't had the chance to test it. If you can test that would be great!

**Review by denvoros — APPROVED** [review]

**Pull request merged**
